services:
  jenkins:
    build:
      context: ./docker
      dockerfile: Dockerfile.jenkins-image
    container_name: jenky-jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace/jenky-src:ro
    environment:
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true

volumes:
  jenkins_home:
